## Spring Boot Actuator Info Endpoint Customization
info:
  # static properties
  app:
    name: Ticketing Sysytem 
    description: Ticketing Sysytem Info Endpoint.
  # build properties from maven
  build:
    groupId: @project.groupId@
    artifact: @project.artifactId@
    name: @project.name@
    version: @project.version@
  # environment variables
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}
spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
  profiles:
    active:
    - Test
    
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: ticketing-system
    key-password: ticket
    key-store: classpath:keystore.jks
    key-store-provider: SUN
    key-store-type: JKS
    key-store-password: ticket
        
endpoints:
  actuator:
    enabled: true
    sensitive: false
  beans:
    enabled: false
  configprops:
    enabled: false
  dump:
    enabled: true
  shutdown:
    enabled: true
  trace:
    sensitive: true
  
    
logging:
  level:
    ROOT: INFO
    # org.hibernate.type.descriptor.sql: TRACE
    # org.springframework.security: TRACE
    